name: Update AMI in ASG Launch Template Production

on:
  workflow_dispatch

jobs:
  update-ami:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into Instance and Pull Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Commands to prepare the instance before AMI creation if needed
            # Navigate to the directory

            # Fetch the latest changes from the repository
            git fetch

            # Checkout the desired branch
            git checkout master

            git pull origin master

      - name: Initialize Terraform
        run: |
          cd terraform/
          terraform init

      # Import existing resources into Terraform state
      - name: Import Resources
        run: |
          cd terraform/
          terraform import aws_subnet.private_subnet_2 ${{ secrets.PROD_PRIVATE_SUBNET_2 }}
          terraform import aws_security_group.alb_sg ${{ secrets.SECURITY_GROUP_ID }}
          terraform import aws_lb.app_lb ${{ secrets.APIS_ALB_ARN }}
          terraform import aws_lb_target_group.app_tg ${{ secrets.APIS_ALB_TG_ARN }}
          terraform import aws_lb_listener.app_listener_http ${{ secrets.ALB_HTTP_LISTENER }}
          terraform import aws_lb_listener.app_listener_https ${{ secrets.ALB_HTTPS_LISTENER }}
          terraform import aws_launch_template.launch_template ${{ secrets.APIS_ASG_LT_ID }}
          terraform import aws_autoscaling_group.app_asg ${{ secrets.ASG_NAME }}

      - name: Apply Changes
        run: |
          cd terraform/
          terraform apply -auto-approve